feat(main-visual.component): トップ画面のメインビジュアル画面を作成しました #37
camp-team/Takeme pull request #38
Opened 2020-06-29 11:39 UTC by akanamori77

#37 

以下の作業を行いました。
御確認お願いします。

- [ ] Top画面のMain-visual画面のModule,Component,routing追加
- [ ] Main-visual画面にダミー画像挿入
- [ ] 検索マークアップ追加

<img width="1431" alt="スクリーンショット 0032-06-29 午後8 38 50" src="https://user-images.githubusercontent.com/64081459/86000491-95b06b00-ba48-11ea-9096-5539613d7c4f.png">

2020-06-30 01:31 UTC, dninomiya requested changes

2020-06-30 01:31 UTC, deerboy commented on src/app/main-visual/main-visual.component.scss
> +#form5 {
idに対してスタイルを当てない
https://to.camp/lesson?v=9czifuwiSf3Qi21PafRj#ID%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%92%E5%BD%93%E3%81%A6%E3%82%8B

2020-06-30 12:52 UTC, deerboy commented
@akanamori77 
修正が終わったらご連絡ください! ✅

2020-06-30 12:57 UTC, akanamori77 commented on src/app/main-visual/main-visual.component.scss
> +#form5 {
@deerboy 

こちら変更完了しております！

2020-07-01 01:56 UTC, dninomiya approved these changes

2020-07-01 01:56 UTC, merged

2020-07-01 01:56 UTC, deerboy commented
GJ!